@api = http://localhost:3000/api

### post login
POST {{api}}/user/login
Content-Type: application/json

{
  "usu_email": "jorejuelam@unicauca.edu.co",
  "usu_contrasena": "juan123"
}

### post labor
POST {{api}}/labor
Content-Type: application/json

{
  "lab_nombre": "Laboratorio 1",
  "lab_descripcion": "Laboratorio de sistemas",
  "lab_estado": "1",
  "lab_tipo": "1",
  "lab_capacidad": "20",
  "lab_imagen": "https://www.unicauca.edu.co/versionP/imagenes/2017/11/20171127_1620_1.jpg",
  "lab_ubicacion": "Bloque 1"
}

### get labors
GET {{api}}/labor