@api = http://localhost:3000/api

### post login
POST {{api}}/user/login
Content-Type: application/json

{
  "usu_email": "jorejuelam@unicauca.edu.co",
  "usu_contrasena": "juan123"
}

### get profile
GET {{api}}/user/profile

### post register
POST {{api}}/user/register
Content-Type: application/json

{
  "userId": 10101010,
  "userName": "Usuario",
  "userLastName": "Prueba",
  "userGenre": "M",
  "userStudy": "Ingenieria en sistemas",
  "userEmail": "juanorejuela499@gmail.com",
  "userPassword": "juan123",
  "usuRol": "docente"
}

### post logout
POST {{api}}/user/logout
Content-Type: application/json

### get professors
GET {{api}}/user/professors